### ISSUE TITLE
If a project has no errors, ziglint should print nothing

### ISSUE THREAD

**Issue by scheibo** [AnnikaCodes/ziglint#8]
https://en.wikipedia.org/wiki/Unix_philosophy

> Don't clutter output with extraneous information.

```
warning: no valid ziglint.json found! using default configuration.
using Gitignore /Users/kjs/Code/src/github.com/pkmn/engine/.gitignore
```

This is just noise - these lines seem like they should be printed only if some sort of `--debug` or `--verbose` flag is passed. Alternatively, if you do feel these are critical to print always, a `--silent` flag should be added to allow users to remove them.

**Comment by AnnikaCodes** [comment]
Done in 3f90249!
